# Usar uma imagem base com Java
FROM openjdk:17-jdk-slim

# Diretório de trabalho dentro do container
WORKDIR /app

# Copiar o JAR da aplicação para o container
RUN ./mvnw clean package -DskipTests
COPY target/api-0.0.1-SNAPSHOT.jar app.jar

# Expor a porta usada pela aplicação Spring Boot (geralmente 8080)
EXPOSE 8080

# Comando para rodar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]